# This workflow runs checks on pushes to main and on pull requests.
name: CI

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ['Lint and Commit']
    types:
      - completed

# Ensures that only one workflow run is triggered for a given branch or PR,
# cancelling any previous runs in progress.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .node-version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .node-version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type checker
        run: pnpm typecheck

  build-and-test-docker:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: unmonitorr-ci:${{ github.sha }}

      - name: Run container
        env:
          RADARR_API_KEY: ci-test
          SONARR_API_KEY: ci-test
        run: docker run -d --name unmonitorr-test -p 9797:9797 -e RADARR_API_KEY -e SONARR_API_KEY unmonitorr-ci:${{ github.sha }}

      - name: Wait for container to be healthy
        run: |
          set -e
          echo "Waiting for container to become healthy..."
          for i in $(seq 1 30); do
            status=$(docker inspect -f '{{.State.Health.Status}}' unmonitorr-test)
            if [ "$status" = "healthy" ]; then
              echo "Container is healthy!"
              exit 0
            fi
            sleep 1
          done
          echo "Container did not become healthy in 30 seconds."
          exit 1

      - name: Show container logs
        if: failure()
        run: docker logs unmonitorr-test

      - name: Stop and remove container
        if: always()
        run: docker rm -f unmonitorr-test
